version: '2'

services:

  nodered:
    image: nodered/node-red-docker
    volumes:
      - ~/mynodered-data:/data
    ports:
      - "1880:1880"
    networks:
      - hano

  haproxy:
    build:
      context: haproxy/
    ports:
      - "80:80"
    networks:
      - hano

networks:
  hano:
    driver: bridge
